package com.marcin;

import java.sql.SQLException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PrepareData {

	private static final Logger log = LoggerFactory.getLogger(App.class);
	private static HsqlConnect hsqlConnect = HsqlConnect.getDbCon();
	public static void createTables() throws SQLException {

		final String CREATE_TABLE_STUDENT = "CREATE TABLE STUDENT (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, name VARCHAR(255), sex VARCHAR(6), age INTEGER, level INTEGER)";
		final String CREATE_TABLE_FACULTY = "CREATE TABLE FACULTY (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY, name VARCHAR(255))";
		final String CREATE_TABLE_CLASS = "CREATE TABLE CLASS (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000, INCREMENT BY 1) PRIMARY KEY, name VARCHAR(255), fkey_faculty INTEGER, FOREIGN KEY (fkey_faculty) REFERENCES FACULTY(id))";
		final String CREATE_TABLE_ENROLLMENT = "CREATE TABLE ENROLLMENT (fkey_student INTEGER, fkey_class INTEGER, FOREIGN KEY (fkey_student) REFERENCES STUDENT(id), FOREIGN KEY (fkey_class) REFERENCES CLASS(id))";

		log.debug("Creation of table STUDENT");
		hsqlConnect.update(CREATE_TABLE_STUDENT);
		log.debug("Table STUDENT was created");

		log.debug("Creation of table FACULTY");
		hsqlConnect.update(CREATE_TABLE_FACULTY);
		log.debug("Table FACULTY was created");

		log.debug("Creation of table CLASS");
		hsqlConnect.update(CREATE_TABLE_CLASS);
		log.debug("Table CLASS was created");

		log.debug("Creation of table ENROLLMENT");
		hsqlConnect.update(CREATE_TABLE_ENROLLMENT);
		log.debug("Table ENROLLMENT was created");
	}

	public static void insertData() throws SQLException {
		
		final String INSERT_STUDENTS = "INSERT INTO STUDENT (name, sex, age, level) VALUES ('John Smith', 'male', 23, 2), ('Rebecca Milson', 'female', 27, 3), ('George Heartbreaker', 'male', 19, 1), ('Deepika Chopra', 'female', 25, 3)";
		final String INSERT_FACULTIES = "INSERT INTO FACULTY(name) VALUES ('Engineering'), ('Philosophy'), ('Law and administration'), ('Languages')";
		final String INSERT_CLASSES = "INSERT INTO CLASS(name, fkey_faculty) VALUES ('Introduction to labour law', 102), ('Graph algorithms', 100), ('Existentialism in 20th century', 101), ('English grammar', 103), ('From Plato to Kant', 101)";
		final String INSERT_ENROLLMENTS = "INSERT INTO ENROLLMENT(fkey_student, fkey_class) VALUES (1, 1000), (1, 1002), (1, 1003), (1, 1004), (2, 1002), (2, 1003), (4, 1000), (4, 1002), (4, 1003)";
		
		log.debug("Start insert students");
		hsqlConnect.update(INSERT_STUDENTS);
		log.debug("End insert students");
		
		log.debug("Start insert faculties");
		hsqlConnect.update(INSERT_FACULTIES);
		log.debug("End insert faculties");
		
		log.debug("Start insert classes");
		hsqlConnect.update(INSERT_CLASSES);
		log.debug("End insert classes");
		
		log.debug("Start insert enrollments");
		hsqlConnect.update(INSERT_ENROLLMENTS);
		log.debug("End insert enrollments");
	}

}
